### ISSUE TITLE
Style Tiles

### ISSUE THREAD

**Issue by dmerrill88** [amacduff/tiy_assignments#2]
Your first tile’s colors and patterns seem to be what the original works of art were like in your movement. The darker colors all work well with each other. The font is pretty regular. You could find some better font to make it look a little trippy like the flag you showed us in class.

For your second tile it looks like you stuck to primary and secondary colors. The last pattern in this one is what makes me think of your movement the most. The four colors are just different shades of the same two colors. Maybe add some very different ones to make your site pop out like your designs do so well.

I enjoyed your third tile the most; The bright colors, the first pattern, and your font text color is fun. My favorite pattern in this tile is your first one. I think you could find some better fonts for this tile that would go better with the patterns you chose.

**Comment by amacduff** [comment]
Thanks for the feedback!
