### ISSUE TITLE
Style Tiles

### ISSUE THREAD

**Issue by rpainterj** [amacduff/tiy_assignments#3]
Style tiles 1 and 3 are working well. I think a lot of your direction depends on how you incorporate the shapes and stripes of op-art. Those can quickly become such a headache that you would have to play down all your other elements. The first palette is pretty classic, but i also like the yellow and pink combination on the third palette. Maybe you could combine those somehow. To me, Montserrat works best for the headers. It's not too flashy and is not as dramatic as Josefin. Orbitron reads a little too futuristic.
You could definitely get some sweet css animations going as well. The simpler you keep the type, the more I think you can achieve. Also, I really like the link styling from palette three. Use that.

**Comment by amacduff** [comment]
Thanks for the feedback!
