### ISSUE TITLE
zen style tile feedback

### ISSUE THREAD

**Issue by eschilb** [amacduff/tiy_assignments#4]
The style tiles look well put together, and out of the three I think the first one has the best proportions and also the overall design works well. I think the fonts all work in conjunction, the sizes work well together, and the color palette fits the mood words. In contrast, I also like the playfulness of the second and third tiles so if you go with those or use aspects from those tiles maybe play around with the boldness of font weights and also with gradients or maybe add additional colors to the palettes for some gradient-like textures.

**Comment by amacduff** [comment]
Thanks for the feedback!
