### ISSUE TITLE
czz zen garden styling

### ISSUE THREAD

**Issue by ellcorey** [amacduff/tiy_assignments#5]
I would like to see,
#### Style #01:
- an additional pattern/"illusion" showing the movement that the op-art movement was known for
- either a darker grey or black for the sub header
#### Style #02:
- a neutral color in place of the orange or yellow
- a header font with a more subdued modern feel
#### Style #03:
- a deeper shade of purple on this tile, it may give the text a little more hierarchy
- a little more black/white contrast, I feel the op-art movement had a bunch of black and white or neutral, contrasting patterns

Overall, I like the direction of style #01, but would like to see a hint of another deep color, and more of the optical illusion/black & white contrasting patterns.

**Comment by amacduff** [comment]
Thanks for the feedback!
