### ISSUE TITLE
CSS Zen Garden Style Tiles

### ISSUE THREAD

**Issue by emilydevoll** [amacduff/tiy_assignments#6]
I would have to say the one I like the most is the first one. It is easy to read, visually appealing, suits your given adjectives, and the patterns you provided give a good idea of where you're going to take it in relation to your art movement theme. The chevron print in comparison to your color choices is a great combo and I hope you incorporate it a lot into your design. (I may steal your text font for mine by the way!)

From the second, I like the header font choice the best out of your other choices. I'm a little confused with the direction this one would go though based off of your visuals. The green striped/leaf-looking picture is mainly what's throwing me off, I feel like its a bit disconnected from your color choices. Maybe if you used green instead of the orange?

The third is the riskiest by far, but if pulled off I think it could make the most impact out of the three. Heads up with using the lime green for the header, when I was trying to use it for our restaurant redesign I realized super fast that it can be a little hard to read unless it's used with a super bold font. The visuals you give are spot on with your color choices and are what make me interested in seeing what you could make from this.

Overall, I think the direction you're going with is great and I'm excited to see which one you choose and how you incorporate all of the elements you've given. Good job!

**Comment by amacduff** [comment]
Thanks for the feedback!
