### ISSUE TITLE
CSS Zen Garden Feedback

### ISSUE THREAD

**Issue by abbylarner** [amacduff/tiy_assignments#7]
Great job exploring different possibilities with this one. I know it wasn't easy.

Style Tile 1:
- Color-wise, I think this one is the strongest in conveying op art.  I would definitely focus on using mostly the black and white and using the other colors as accents
- The type also works really nicely together.  It is readable, and I understand why you chose the typefaces that you chose.  My only concern with the header is that it might be too safe.  That being said, I can see it working well if you bring in the line-art elements elsewhere on the page
- Push  yourself with the design of the link! See what is out there.  Because links are smaller elements, you could do something really cool with the link to make it more op-arty (possibly animate it with some css too?)

Style Tile 2:
- The colors on this one are definitely exciting and contrast nicely.
- This one reads a little too "futuristic" but mostly because of the typeface you chose

Style Tile 3:
- I definitely appreciate the craziness of this style tile.  I think there are certain elements here that could work nicely with the first style tile, but may be a bit too far (good job pushing it!)
- The text link is a bit more interesting in this one than in the first one, but I think the header typeface might be a bit too humanist for op art.  I think the strong lines in the first style tile work best for the op-art feel

**Comment by amacduff** [comment]
Thanks for the feedback! I think I'm going to go with Style Tile 1. I may play with the addition of another contrasting color and a different heading typeface, in which case I might want some additional feedback. Thanks in advance!
