### ISSUE TITLE
Homework Week 3 & 4

### ISSUE THREAD

**Issue by abbylarner** [amacduff/tiy_assignments#8]
Suggestions for the future:
- Sitemaps should look more like flow charts than lists
- Push even further with wordlists (more words). The more words you have, the more you will be able to push past the obvious

Things that need to be fixed/finished:
- Right navigation in Pocket app is wrapping underneath logo before the smallest breakpoint
- Missing Blog post on typographic discoveries
- Fix merge conflicts on Easy Tiger menu page (the design is broken right now)
- Turn in CSS Animation codepens

**Comment by amacduff** [comment]
Suggestions for the future:
- Man, I knew I shouldn't have done it that way. I had so many top-level links that I kept running out of space when I tried to fit them on one line, so I listed them like that. Laziness, I guess. I won't do that again.
- I'll definitely try to push myself more next time. Wordlists and mindmapping have always been challenging for me. I definitely don't want to settle on the easiest solution in my designs.

Things that need to be fixed/finished:
- Wrapping navigation! Embarrassing!! Talk about a lack of attention to detail... Anyway, I took another look at the Get Pocket site and it looks like their nav doesn't switch til 608px, so I added another breakpoint there to accommodate the nav getting bigger. Is that an acceptable solution?
- I finished my blog post and pushed it to my "_posts" folder, under "tiy_assignments."
- Menu page fixed. I've learned my lesson about pulling/pushing from different computers.
- Added README with Codepen links to "day_17" folder. I had pushed one, but it got lost in my little Git mishap.

Sorry I got so behind on homework, I had no idea I was even behind at all. Thanks for all your help.
